Homework 7
### Lei Jiang


Imagine you are an Engineer for Amazon Alexa.  You are given the task of understanding text input and classifying it.  Create a data set of sayings that fall into 2 Categories: Getting Directions and Playing Music.  Make sure you data set has at least 100 examples total.

Example Playing Music:
"Play some Pantera on Spotify"

Example Directions:
"Where is the nearest Starbucks"

In [1]:
# from warnings import simplefilter
# import json
# import statistics
# import seaborn as sns
# import matplotlib.pyplot as plt
# from itertools import product
# from sklearn import datasets
# from sklearn.model_selection import KFold
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import numpy as np
simplefilter(action='ignore', category=FutureWarning)

In [52]:
import pandas as pd
#import the data
directory = 'C:/Users/N1110/Desktop/'
df = pd.read_csv(directory + 'AlexaData.csv') #, header=True


In [36]:
df.head(5)

Sentence  Label
0               play music    1.0
1  play most popular songs    1.0
2       play spotify songs    1.0
3         play my playlist    1.0
4  play the song by lyrics    1.0

In [37]:
df['Sentence'].astype(str)

0                               play music
1                  play most popular songs
2                       play spotify songs
3                         play my playlist
4                  play the song by lyrics
                      ...                 
95            Get directions to bay bridge
96    Get directions to golden gate bridge
97      Get directions to joshua tree park
98          Get directions to palm springs
99     Get directions to good sam hospital
Name: Sentence, Length: 100, dtype: object

In [38]:
df.shape

(100, 2)

In [39]:
data1 = np.array(df.Sentence)
data1

array(['play music', 'play most popular songs', 'play spotify songs',
       'play my playlist', 'play the song by lyrics',
       'alexa play music everywhere', 'play iheart radio', 'play pandora',
       'play prime music', 'play apple music',
       'play songs from charlie puth', 'play senorita',
       'play girls like you', 'what is the most popular songs this week',
       'play top songs from Mariah Carey', 'play songs from Katy Perry',
       'play songs from Taylor Swift',
       'play songs from charlie puth and Ariana Grande',
       'play songs from Frank Sinatra', 'play top songs from Roar radio',
       'play firework', "play Taylor Swift's newest song",
       'play songs from Ariana Grande',
       'play Fly me to the moon from Frank Sinatra',
       'i want to listen to Shakira', 'play Shakira songs',
       'play top songs from Shawn Mendes', 'play some Celine Dion songs',
       'any new song from Camila Cabello', 'play new song from Sia',
       'play most popular 

In [40]:
data3= ['play music', 'play most popular songs', 'play spotify songs',
       'play my playlist', 'play the song by lyrics',
       'alexa play music everywhere', 'play iheart radio', 'play pandora',
       'play prime music', 'play apple music',
       'play songs from charlie puth', 'play senorita',
       'play girls like you', 'what is the most popular songs this week',
       'play top songs from Mariah Carey', 'play songs from Katy Perry',
       'play songs from Taylor Swift',
       'play songs from charlie puth and Ariana Grande',
       'play songs from Frank Sinatra', 'play top songs from Roar radio',
       'play firework', "play Taylor Swift's newest song",
       'play songs from Ariana Grande',
       'play Fly me to the moon from Frank Sinatra',
       'i want to listen to Shakira', 'play Shakira songs',
       'play top songs from Shawn Mendes', 'play some Celine Dion songs',
       'any new song from Camila Cabello', 'play new song from Sia',
       'play most popular songs this month',
       'play most popular songs in 2019', 'play beethoven symphony 9',
       'play symphony', 'play some sam smith songs',
       "play Mariah Carey's hero", 'play the songs from movie skyfall',
       'play skyfall from adele', 'play the world is not enough song',
       'play some marvin gaye', 'play wrtings on the wall',
       'play some kylie minogue songs', 'play some k-pop',
       'play some piano music', 'play some meditation music',
       'play some pop music from pandora',
       'play some music from George Michael ', 'play some Beyonce',
       'play some Queen from spotify', 'Get directions to New York',
       'Get directions to Dallas', 'take me to nearest book store',
       'where is the nearest Pharmacy',
       'where is the nearest supermarket',
       'take me to aquarium of the bay',
       'where is the nearest art museum',
       'where is the nearest movie theatre',
       'where is the nearest rose garden',
       'take me to Millennium park in chicago',
       'get directions to shedd aquarium ',
       'where is the nearest wholefoods',
       'Get directions to Ohio University', 'Get directions to Ohio',
       'Get directions to SJSU', 'Get directions to Hawaii',
       'Get directions to google', 'Get directions to stanford',
       'Get directions to san francisco airport', 'take me to Dartmouth',
       'where is the nearest Starbucks', 'where is the nearest CVS',
       'where is the nearest hospital',
       'where is the nearest chinese restaurant ',
       'where is the nearest sichuan restaurant ',
       'where is the nearest hunan restaurant ',
       'where is the best French restaurant ',
       'Get directions to Saratoga downtown',
       'where is the nearest mcdonalds',
       'where is the nearest gas station', 'where is the nearest zoo',
       "take me to Leah's school", 'Get directions to lake tahoe',
       'Get directions to stanford shopping center',
       'Get directions to las vegas', 'Get directions to Disney world',
       'Get directions to Hollywood ',
       'Get directions to San Jose airport', "take me to Job's home",
       'take me to work', "take me to Leah's home",
       'where is the nearest mall', 'where is the nearest safeway',
       'Get directions to sea world', 'where is the nearest homedepot',
       'where is the nearest costco', 'Get directions to bay bridge',
       'Get directions to golden gate bridge',
       'Get directions to joshua tree park',
       'Get directions to palm springs',
       'Get directions to good sam hospital']

In [41]:
data3

['play music',
 'play most popular songs',
 'play spotify songs',
 'play my playlist',
 'play the song by lyrics',
 'alexa play music everywhere',
 'play iheart radio',
 'play pandora',
 'play prime music',
 'play apple music',
 'play songs from charlie puth',
 'play senorita',
 'play girls like you',
 'what is the most popular songs this week',
 'play top songs from Mariah Carey',
 'play songs from Katy Perry',
 'play songs from Taylor Swift',
 'play songs from charlie puth and Ariana Grande',
 'play songs from Frank Sinatra',
 'play top songs from Roar radio',
 'play firework',
 "play Taylor Swift's newest song",
 'play songs from Ariana Grande',
 'play Fly me to the moon from Frank Sinatra',
 'i want to listen to Shakira',
 'play Shakira songs',
 'play top songs from Shawn Mendes',
 'play some Celine Dion songs',
 'any new song from Camila Cabello',
 'play new song from Sia',
 'play most popular songs this month',
 'play most popular songs in 2019',
 'play beethoven symphony 9',
 'p

In [80]:
# the labels 
# music：1
# navigation: 0
L = pd.DataFrame(np.array(df['Label']))
L.columns = ['Label']
L

Label
0       1
1       1
2       1
3       1
4       1
..    ...
95      0
96      0
97      0
98      0
99      0

[100 rows x 1 columns]

In [18]:

data2 =[
    "The quick brown fox jumps over the lazy dog.",
    "I am a sentence for which I would like to get its embedding",
    "This is a test and only a test"]
#test data

In [20]:
data2

['The quick brown fox jumps over the lazy dog.',
 'I am a sentence for which I would like to get its embedding',
 'This is a test and only a test']

Q1 Given the following module that outputs a vector which represents your input sentence, transform your data into numbers.

In [11]:
import tensorflow as tf
import tensorflow_hub as hub
print(tf.__version__)

1.13.1


In [12]:
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/3")
#this step takes long

NotImplementedError: hub.load() is not implemented for TF < 1.14.x, Current version: 1.13.1

In [26]:
embeddings = embed(data2)["outputs"]

print(embeddings)

tf.Tensor(
[[-0.03133016 -0.06338635 -0.01607501 ... -0.0324278  -0.04575742
   0.05370458]
 [ 0.05080862 -0.01652429  0.01573782 ...  0.0097666   0.03170121
   0.01788118]
 [ 0.01015075 -0.06261258 -0.02163218 ... -0.05879759  0.00330179
   0.02137555]], shape=(3, 512), dtype=float32)


In [27]:
embeddings.shape

TensorShape([3, 512])

In [43]:
embeddings = embed(data3)["outputs"]

print(embeddings)

tf.Tensor(
[[-0.0243762   0.01918176  0.07996774 ... -0.05385037  0.02100432
   0.03922744]
 [-0.066237   -0.03749611  0.09285352 ... -0.01519213 -0.07086826
   0.06833539]
 [ 0.01012249 -0.00309336  0.08013065 ...  0.00325632 -0.07294104
   0.04892665]
 ...
 [ 0.03722878  0.02177463  0.05397604 ...  0.00583609 -0.0232576
   0.02819966]
 [ 0.06316751  0.06211495 -0.05519738 ...  0.02400611 -0.03641595
  -0.02009307]
 [ 0.02083507  0.03593273 -0.02815449 ...  0.01445058  0.06802659
   0.02509072]], shape=(100, 512), dtype=float32)


In [44]:
embeddings.shape

TensorShape([100, 512])

Q2: Take your numbers from Q1 and create 2 classifiers of any type.  What is your best guess for the accuracy of your models. (Don't forget to use good data science practices!)

#### ANSWER:
#### My guess is the accuracy would be high above 90%.

#### From running the models below I found the best accuracy is 100% for both SVM and RF (vanllia models, without parameter tuning).

#### roc_auc_score are also both very high:
##### Random Forest - roc_auc_score:  0.9615384615384616 or Random Forest - roc_auc_score:  0.95
##### SVM - - roc_auc_score:  0.9615384615384616 or SVM - - roc_auc_score:  0.9375

####  It is a good experiment for small sample size classification ML modeling. I had 80,20 split of train and test data. so there are only 20 samples for test data set. For this small sample size, RF is less stable than SVM, sometimes, Random Forest - acc:  0.65 while SVM accuracy is  always 1.0 among shuffles (>3 times).

In [76]:
M=pd.DataFrame(np.array(embeddings))
M

0         1         2         3         4         5         6    \
0  -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
1  -0.066237 -0.037496  0.092854 -0.021869 -0.071633  0.027011 -0.014636   
2   0.010122 -0.003093  0.080131 -0.001090 -0.042481  0.000824 -0.035859   
3   0.006381  0.030609  0.088412 -0.043798 -0.040280  0.040256  0.005590   
4   0.051047 -0.012177  0.090686 -0.000063 -0.057425  0.009228 -0.067784   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.009347  0.057388 -0.024002  0.014735 -0.036514 -0.030377 -0.025915   
96  0.044108 -0.011704 -0.015650 -0.034613 -0.002636 -0.075151 -0.041565   
97  0.037229  0.021775  0.053976  0.035653 -0.054273  0.079331 -0.027004   
98  0.063168  0.062115 -0.055197 -0.002553 -0.050561  0.014561  0.044589   
99  0.020835  0.035933 -0.028154  0.011338  0.043762 -0.005391  0.063510   

         7         8         9    ...       502       503       504       505  \
0  -0.002503  0.052732  0.009590  ...  0.038410 -0.079658  0.062860  0.052881   
1  -0.031274 -0.054216  0.011073  ...  0.075788 -0.033672  0.061179  0.012517   
2  -0.061345 -0.054698 -0.029774  ...  0.044324 -0.042988  0.051780 -0.006322   
3  -0.003294 -0.023361  0.053098  ...  0.016929 -0.077994  0.075236 -0.007940   
4  -0.031167 -0.081383  0.076666  ...  0.005288  0.010229  0.028551 -0.024727   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.027997  0.001785  0.048643  ... -0.054296  0.001853  0.046345  0.041187   
96 -0.007872  0.015522 -0.007903  ... -0.034856  0.029189  0.019134  0.000134   
97  0.003454  0.059319 -0.029738  ... -0.025030  0.042878 -0.013334  0.051205   
98 -0.037766 -0.036218 -0.025266  ...  0.005474 -0.006851  0.055414 -0.016784   
99  0.021658  0.018669 -0.071306  ... -0.037284  0.047534  0.005676 -0.083473   

         506       507       508       509       510       511  
0  -0.000144  0.050155 -0.000216 -0.053850  0.021004  0.039227  
1  -0.015844  0.041240  0.009088 -0.015192 -0.070868  0.068335  
2  -0.069571  0.007340  0.022173  0.003256 -0.072941  0.048927  
3  -0.000168  0.020954  0.047006  0.019413 -0.011335  0.037455  
4   0.034883 -0.016907 -0.016865 -0.018148 -0.061806  0.043755  
..       ...       ...       ...       ...       ...       ...  
95  0.012807  0.057949 -0.047685  0.002285 -0.032715  0.027635  
96  0.017566  0.050397 -0.067017  0.034545 -0.033566 -0.000945  
97 -0.087107  0.061601  0.002635  0.005836 -0.023258  0.028200  
98 -0.082624  0.090812  0.059221  0.024006 -0.036416 -0.020093  
99 -0.002082  0.015692  0.038929  0.014451  0.068027  0.025091  

[100 rows x 512 columns]

In [81]:
df_clean= pd.concat((M, L), axis=1)

In [82]:
df_clean

0         1         2         3         4         5         6  \
0  -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
1  -0.066237 -0.037496  0.092854 -0.021869 -0.071633  0.027011 -0.014636   
2   0.010122 -0.003093  0.080131 -0.001090 -0.042481  0.000824 -0.035859   
3   0.006381  0.030609  0.088412 -0.043798 -0.040280  0.040256  0.005590   
4   0.051047 -0.012177  0.090686 -0.000063 -0.057425  0.009228 -0.067784   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.009347  0.057388 -0.024002  0.014735 -0.036514 -0.030377 -0.025915   
96  0.044108 -0.011704 -0.015650 -0.034613 -0.002636 -0.075151 -0.041565   
97  0.037229  0.021775  0.053976  0.035653 -0.054273  0.079331 -0.027004   
98  0.063168  0.062115 -0.055197 -0.002553 -0.050561  0.014561  0.044589   
99  0.020835  0.035933 -0.028154  0.011338  0.043762 -0.005391  0.063510   

           7         8         9  ...       503       504       505       506  \
0  -0.002503  0.052732  0.009590  ... -0.079658  0.062860  0.052881 -0.000144   
1  -0.031274 -0.054216  0.011073  ... -0.033672  0.061179  0.012517 -0.015844   
2  -0.061345 -0.054698 -0.029774  ... -0.042988  0.051780 -0.006322 -0.069571   
3  -0.003294 -0.023361  0.053098  ... -0.077994  0.075236 -0.007940 -0.000168   
4  -0.031167 -0.081383  0.076666  ...  0.010229  0.028551 -0.024727  0.034883   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.027997  0.001785  0.048643  ...  0.001853  0.046345  0.041187  0.012807   
96 -0.007872  0.015522 -0.007903  ...  0.029189  0.019134  0.000134  0.017566   
97  0.003454  0.059319 -0.029738  ...  0.042878 -0.013334  0.051205 -0.087107   
98 -0.037766 -0.036218 -0.025266  ... -0.006851  0.055414 -0.016784 -0.082624   
99  0.021658  0.018669 -0.071306  ...  0.047534  0.005676 -0.083473 -0.002082   

         507       508       509       510       511  Label  
0   0.050155 -0.000216 -0.053850  0.021004  0.039227      1  
1   0.041240  0.009088 -0.015192 -0.070868  0.068335      1  
2   0.007340  0.022173  0.003256 -0.072941  0.048927      1  
3   0.020954  0.047006  0.019413 -0.011335  0.037455      1  
4  -0.016907 -0.016865 -0.018148 -0.061806  0.043755      1  
..       ...       ...       ...       ...       ...    ...  
95  0.057949 -0.047685  0.002285 -0.032715  0.027635      0  
96  0.050397 -0.067017  0.034545 -0.033566 -0.000945      0  
97  0.061601  0.002635  0.005836 -0.023258  0.028200      0  
98  0.090812  0.059221  0.024006 -0.036416 -0.020093      0  
99  0.015692  0.038929  0.014451  0.068027  0.025091      0  

[100 rows x 513 columns]

In [124]:
df_imputed=df_clean


from sklearn.model_selection import ShuffleSplit

# we want to predict the X and y data as follows:
if 'Label' in df_imputed:
    y = df_imputed['Label'].values # get the labels we want
    del df_imputed['Label'] # get rid of the class label
    X = df_imputed.values # use everything else to predict!


num_cv_iterations = 3
num_instances = len(y)
cv_object = ShuffleSplit(n_splits=num_cv_iterations,
                         test_size  = 0.2)
                         
print(cv_object)

ShuffleSplit(n_splits=3, random_state=None, test_size=0.2, train_size=None)


In [125]:
## Training and Testing Split
# okay, so run through the cross validation loop and set the training and testing variable for one single iteration
for train_indices, test_indices in cv_object.split(X,y): 
 
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]

In [126]:

from sklearn.preprocessing import StandardScaler
scl_obj = StandardScaler()

scl_obj.fit(X_train)
X_test_scaled = scl_obj.transform(X_test)

X_train_scaled = scl_obj.transform(X_train) # apply to training
X_test_scaled = scl_obj.transform(X_test) 

In [127]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

rf_clf = RandomForestClassifier( criterion = 'gini', 
                                n_estimators = 5, verbose = False)
rf_clf.fit(X_train_scaled,y_train)

preds = rf_clf.predict(X_test_scaled)
    
    
print('Random Forest - roc_auc_score: ', roc_auc_score(y_test, preds))
#Random Forest - roc_auc_score:  0.9615384615384616

Random Forest - roc_auc_score:  0.95


In [128]:
acc = mt.accuracy_score(y_test,y_hat)
conf = mt.confusion_matrix(y_test,y_hat)

print('Random Forest - acc: ', acc)
print(conf)

Random Forest - acc:  0.6
[[6 4]
 [4 6]]


In [129]:
# lets investigate SVMs on the data and play with the parameters and kernels
#%%time
#try run with all medications

from sklearn.svm import SVC

# train the model just as before
svm_clf = SVC(C=0.5, kernel='rbf', degree=3, gamma='auto') # get object
svm_clf.fit(X_train_scaled, y_train)  # train object

y_hat = svm_clf.predict(X_test_scaled) # get test set precitions

In [130]:
#get SVM ACC

from sklearn import metrics as mt

acc = mt.accuracy_score(y_test,y_hat)
conf = mt.confusion_matrix(y_test,y_hat)

print('SVM accuracy:', acc )
print(conf)


SVM accuracy: 1.0
[[10  0]
 [ 0 10]]


In [131]:
print('SVM - - roc_auc_score: ', roc_auc_score(y_test, preds))

SVM - - roc_auc_score:  0.95
